### ISSUE TITLE
E5108: Error executing lua: ...p-args.nvim/lua/telescope/_extensions/live_grep_args.lua:56: attempt to call a nil value

### ISSUE THREAD

**Issue by stephane-klein** [nvim-telescope/telescope-live-grep-args.nvim#36]
Hello,

Since few days, I have this error:

```
E5108: Error executing lua: ...p-args.nvim/lua/telescope/_extensions/live_grep_args.lua:56: attempt to call a nil value
stack traceback:
        ...p-args.nvim/lua/telescope/_extensions/live_grep_args.lua:56: in function 'picker'
        /Users/stephaneklein/.config/nvim/lua/_telescope.lua:158: in function </Users/stephaneklein/.config/nvim/lua/_telescope.lua:158>
```

Here is the error line in my configuration: https://github.com/stephane-klein/dotfiles/blob/079e4e70307fa7aa24c2af9e602d04439d05c3f2/dot_config/nvim/lua/_telescope.lua#L158

Do you have any idea where the problem might be coming from?

Best regards,  
Stéphane

**Comment by stephane-klein** [comment]
If I replace:

```
vim.keymap.set(
    'n', '<leader>/',
    use_layout(telescope.extensions.live_grep_args.live_grep_args, 'popup_list'),
    { noremap = true, desc = "Live ripgrep"}
)
```

by:

```
vim.keymap.set(
    'n', '<leader>/',
    telescope.extensions.live_grep_args.live_grep_args,
    { noremap = true, desc = "Live ripgrep"}
)
```

The bug is fixed.

**Comment by weeman1337** [comment]
Hi @stephane-klein thanks for reporting the issue. It has been introduced by #10 .
Changing the config doesn't fix bugs or issues :)

I will commit an update shortly.

**Comment by weeman1337** [comment]
@stephane-klein can you give #37 a try?

You can set the `improve-theme-support` branch in your packer config.

**Comment by stephane-klein** [comment]
@weeman1337 thinks, it works :+1: 

My config is fixed by https://github.com/stephane-klein/dotfiles/commit/ef7eadce1f043efa0526cced162aa43e80c19a9d
